const expenses = [
  {
    "name": "Allemagne",
    "hebergement": 100,
    "restauration": 3,
    "loisirs": 5,
    "shopping": 13,
    "transport": 17,
    "total": 172,
  },
  {
    "name": "Belgique",
    "hebergement": 105,
    "restauration": 45,
    "loisirs": 3,
    "shopping": 14,
    "transport": 9,
    "total": 176,
  },
  {
    "name": "Chine",
    "hebergement": 61,
    "restauration": 32,
    "loisirs": 19,
    "shopping": 73,
    "transport": 11,
    "total": 197,
  },
  {
    "name": "RoyaumeUni",
    "hebergement": 124,
    "restauration": 42,
    "loisirs": 2,
    "shopping": 17,
    "transport": 17,
    "total": 202,
  },
  {
    "name": "Japon",
    "hebergement": 86,
    "restauration": 38,
    "loisirs": 15,
    "shopping": 66,
    "transport": 11,
    "total": 217,
  },
  {
    "name": "MoyenOrient",
    "hebergement": 72,
    "restauration": 38,
    "loisirs": 16,
    "shopping": 51,
    "transport": 13,
    "total": 190,
  },
  {
    "name": "Russie",
    "hebergement": 74,
    "restauration": 41,
    "loisirs": 19,
    "shopping": 49,
    "transport": 7,
    "total": 191,
  }
]
export default expenses;
